run:
  allow-parallel-runners: true
  timeout: "1m"

linters:
  disable-all: true
  enable:
    - gosimple
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - containedctx
    - contextcheck
    - decorder
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - goerr113
    - gofumpt
    - gosec
    - grouper
    - lll
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nosprintfhostport
    - paralleltest
    - prealloc
    - revive
    - tenv
    - unconvert
    - unparam
    - wastedassign
    - wsl

linters-settings:
  govet:
    enable-all: true
  wsl:
    allow-trailing-comment: true
  decorder:
    disable-dec-order-check: false
    disable-init-func-first-check: false
    disable-dec-num-check: true
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated
    disabled-tags:
      - experimental
    enabled-checks:
      - httpNoBody
      - regexpSimplify
    disabled-checks:
      - hugeParam
  gocognit:
    min-complexity: 20
  funlen:
    lines: 80
    statements: -1

issues:
  exclude-rules:
    - linters:
        - paralleltest
      text: "does not use range value in test"
    - path: _test\.go
      linters:
        - goerr113
        - funlen
    - path: _test\.go
      text: "fieldalignment:"
      linters:
        - govet
