name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -v ./...
